/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalStore;

import javax.swing.JFrame;
import javax.swing.JOptionPane;//
import static sun.text.normalizer.UTF16.append;
/**
 *
 * @author 
 */
public class medicalStore extends javax.swing.JFrame {
private JFrame frame;
    
public String append;
            
    /**
     * Creates new form medicalStore
     */
    public medicalStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtxtDelete = new javax.swing.JButton();
        jtxtDoctor = new javax.swing.JButton();
        jtxtGP = new javax.swing.JButton();
        jtxtPrescription = new javax.swing.JButton();
        jtxtLogin = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jtxtExit = new javax.swing.JButton();
        jtxtUpdate = new javax.swing.JButton();
        jtxtClear = new javax.swing.JButton();
        jtxtRef = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtPossibleSideEffect = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JLabel();
        jtxtIssuedDate1 = new javax.swing.JLabel();
        jtxtFI1 = new javax.swing.JLabel();
        jtxtDose1 = new javax.swing.JLabel();
        jtxtMedicane1 = new javax.swing.JLabel();
        jcmbNT = new javax.swing.JComboBox<>();
        jtxtPossibleSideEffect1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jtxtMedicane = new javax.swing.JTextField();
        jtxtDose = new javax.swing.JTextField();
        jtxtFI = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtExpDate1 = new javax.swing.JTextField();
        jtxtAoP = new javax.swing.JLabel();
        jtxtDailyDose = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtHtui = new javax.swing.JLabel();
        jtxtSe = new javax.swing.JLabel();
        jtxtLot = new javax.swing.JLabel();
        JtxtPName = new javax.swing.JLabel();
        jtxtDoB = new javax.swing.JLabel();
        jtxtNot = new javax.swing.JLabel();
        jtxtAoP1 = new javax.swing.JTextField();
        jtxtDailyDose1 = new javax.swing.JTextField();
        jtxtHtui1 = new javax.swing.JTextField();
        jtxtNot1 = new javax.swing.JTextField();
        jtxtSe1 = new javax.swing.JTextField();
        jtxtRN = new javax.swing.JTextField();
        JtxtPName1 = new javax.swing.JTextField();
        jtxtDoB1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 0));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 490, 400));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jTextField1.setText("Medical Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1360, -1));

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jTextField2.setText("Prescription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 870, -1));

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDelete.setText("Delete");
        jtxtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDeleteActionPerformed(evt);
            }
        });

        jtxtDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDoctor.setText("Doctor");

        jtxtGP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtGP.setText("GP Appointment");

        jtxtPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPrescription.setText("Prescription");
        jtxtPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrescriptionActionPerformed(evt);
            }
        });

        jtxtLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLogin.setText("Login");
        jtxtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLoginActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jtxtExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtExit.setText("Exit");
        jtxtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExitActionPerformed(evt);
            }
        });

        jtxtUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtUpdate.setText("Update");
        jtxtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUpdateActionPerformed(evt);
            }
        });

        jtxtClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtClear.setText("Clear");
        jtxtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtGP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 80));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtRef.setText("Referance No:");
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name Of disease:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jtxtPossibleSideEffect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtPossibleSideEffect.setText("Possible reason of diease:");
        getContentPane().add(jtxtPossibleSideEffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtExpDate.setText("Exp date:");
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 20));

        jtxtIssuedDate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtIssuedDate1.setText("Issued date:");
        getContentPane().add(jtxtIssuedDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jtxtFI1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFI1.setText("Furtur Info:");
        getContentPane().add(jtxtFI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jtxtDose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDose1.setText("Dose(mg):");
        getContentPane().add(jtxtDose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jtxtMedicane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMedicane1.setText("Medicane Name:");
        getContentPane().add(jtxtMedicane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jcmbNT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search for diease", "Headache", "Cough", "Temprature" }));
        jcmbNT.setToolTipText("");
        jcmbNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNTActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 160, 20));
        getContentPane().add(jtxtPossibleSideEffect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 160, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 160, -1));
        getContentPane().add(jtxtMedicane, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 160, -1));
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 160, -1));
        getContentPane().add(jtxtFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 160, -1));
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 160, -1));
        getContentPane().add(jtxtExpDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 160, -1));

        jtxtAoP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtAoP.setText("Address of patient:");
        getContentPane().add(jtxtAoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDailyDose.setText("Daily Dose:");
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jtxtHtui.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtHtui.setText("How to Use it:");
        getContentPane().add(jtxtHtui, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jtxtSe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSe.setText("ML:");
        getContentPane().add(jtxtSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLot.setText("RN:");
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        JtxtPName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtPName.setText("Patient Name:");
        getContentPane().add(JtxtPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        jtxtDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDoB.setText("Date of birth:");
        getContentPane().add(jtxtDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jtxtNot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtNot.setText("No of tablets:");
        getContentPane().add(jtxtNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));
        getContentPane().add(jtxtAoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 200, 40));
        getContentPane().add(jtxtDailyDose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        getContentPane().add(jtxtHtui1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 200, -1));
        getContentPane().add(jtxtNot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 200, -1));
        getContentPane().add(jtxtSe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 200, -1));
        getContentPane().add(jtxtRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 200, -1));
        getContentPane().add(JtxtPName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 200, -1));
        getContentPane().add(jtxtDoB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 200, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referance #", "Patient Name", "Medicane Name", "Dose(mg)", "Issued Date", "Expire Date", "Side Effect", "Daily Dose", "How to Use", "No of Tablets", "ML", "RN", "Further info", "P.Date of birth", "Address of Patient"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 578, 1360, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDeleteActionPerformed

    private void jtxtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExitActionPerformed
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Medical pharmacy",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jtxtExitActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
    
    }//GEN-LAST:event_printActionPerformed

    private void jcmbNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNTActionPerformed
       if(jcmbNT.getSelectedItem().equals("Headache"))
       {
              jTextField4.setText("50BD203");
              jtxtMedicane.setText("Panadol");
              jtxtDose.setText("05");
             jtxtFI.setText("No");
             jtxtIssuedDate.setText("");
             jtxtExpDate1.setText("");
             jtxtPossibleSideEffect1.setText("No");
             jtxtDailyDose1.setText("3");
             jtxtHtui1.setText("Water");
             jtxtNot1.setText("10");
             jtxtSe1.setText("000024");
             jtxtRN.setText("000817");
            JtxtPName1.setText("");
            jtxtDoB1.setText("");
            jtxtAoP1.setText("");
            }
       else    if(jcmbNT.getSelectedItem().equals("Cough"))
       {
              jTextField4.setText("50BD203");
              jtxtMedicane.setText("Cough Scripe");
              jtxtDose.setText("05");
             jtxtFI.setText("No");
             jtxtIssuedDate.setText("");
             jtxtExpDate1.setText("");
             jtxtPossibleSideEffect1.setText("Coz of cold drink or water");
             jtxtDailyDose1.setText("3");
             jtxtHtui1.setText("After Eating something");
             jtxtNot1.setText("Scripe");
             jtxtSe1.setText("000024");
             jtxtRN.setText("000817");
            JtxtPName1.setText("");
            jtxtDoB1.setText("");
            jtxtAoP1.setText("");
             
       
       }
       else    if(jcmbNT.getSelectedItem().equals("Temprature"))
       {
              jTextField4.setText("50BD203");
              jtxtMedicane.setText("Panadol,brufin");
              jtxtDose.setText("05mg,20mg");
             jtxtFI.setText("No");
             jtxtIssuedDate.setText("");
             jtxtExpDate1.setText("");
             jtxtPossibleSideEffect1.setText("Barish ma bheeg jana ki waja sa");
             jtxtDailyDose1.setText("3");
             jtxtHtui1.setText("Use it with Water");
             jtxtNot1.setText("10,10");
             jtxtSe1.setText("000024");
             jtxtRN.setText("000817");
            JtxtPName1.setText("");
            jtxtDoB1.setText("");
            jtxtAoP1.setText("");
       }
       else    if(jcmbNT.getSelectedItem().equals("Search for Diease"))
       {
              jTextField4.setText("");
              jtxtMedicane.setText("");
              jtxtDose.setText("");
             jtxtFI.setText("");
             jtxtIssuedDate.setText("");
             jtxtExpDate1.setText("");
             jtxtPossibleSideEffect1.setText("");
             jtxtDailyDose1.setText("");
             jtxtHtui1.setText("");
             jtxtNot1.setText("");
             jtxtSe1.setText("");
             jtxtRN.setText("");
            JtxtPName1.setText("");
            jtxtDoB1.setText("");
            jtxtAoP1.setText("");
             
       
       }
    }//GEN-LAST:event_jcmbNTActionPerformed

    private void jtxtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLoginActionPerformed

    private void jtxtPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrescriptionActionPerformed
         /*
          String Qty1  = (jTextField4.getText());
          String Qty2  = (jtxtMedicane.getText());
          String Qty3  =  (jtxtDose.getText());
          String Qty4  =  (jtxtFI.getText());
          String Qty5  =  (jtxtIssuedDate.getText());
          String Qty6  =  (jtxtExpDate1.getText());
          String Qty7  =  (jtxtPossibleSideEffect1.getText());
          String Qty8  =  (jtxtDailyDose1.getText());
          String Qty9  =  ( jtxtHtui1.getText());
          String Qty10 =  (jtxtNot1.getText());
          String Qty11 =  (jtxtSe1.getText());
          String Qty12 =  ( jtxtRN.getText());
          String Qty13 =  (JtxtPName1.getText()); 
          String Qty14 =  (jtxtDoB1.getText());
          String Qty15 =   "";
          jtxtPrescription.setText("");
         jtxtPrescription.append("\t\t Medical\t\n"
                  +"Name of patient\t"+Qty13
                  +"\t Date of birth\t"+Qty14
                  +"\t Prescription:\t"+ Qty15
                  +"\t Refrance No:"+Qty1
                  +"\t Name of medicene:\t"+Qty2
                  +"\t Dose(mg):\t"+Qty3
                  +"\t Furtur Information:\t" +Qty4
                  +"\t Issue Date:" + Qty5
                  +"\t Date of Expire:"+Qty6
                  +"\t Side Effects:"+Qty7
                  +"\t Daily Dose:"+ Qty8
                  +"\t Methode of use:" +Qty9
                  +"\t Number of tablets:" + Qty10
                  +"\t ML:"+Qty11
                  +"\t RN:"+Qty12
                 );
          */
         
    }//GEN-LAST:event_jtxtPrescriptionActionPerformed

    private void jtxtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUpdateActionPerformed
   
      /*       DefaultTableMode1 mode1 = (DefaultTableMode1) jTable4.getMode1();
        mode1.addrow(new object[]{jcmbNT.getSelectedItem().toString(),
        jTextField4.getText(),jtxtMedicane.getText(),jtxtDose.getText(),
        jtxtFI.getText(),jtxtIssuedDate.getText(),jtxtExpDate1.getText(),
        jtxtPossibleSideEffect1.getText(),jtxtDailyDose1.getText(),
        jtxtHtui1.getText(),jtxtNot1.getText(),jtxtSe1.getText(),
        jtxtRN.getText(),JtxtPName1.getText(),jtxtDoB1.getText()
                ,jtxtAoP1.getText()  */
    }//GEN-LAST:event_jtxtUpdateActionPerformed

    private void jtxtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClearActionPerformed
 
              jTextField4.setText("");
              jtxtMedicane.setText("");
              jtxtDose.setText("");
             jtxtFI.setText("");
             jtxtIssuedDate.setText("");
             jtxtExpDate1.setText("");
             jtxtPossibleSideEffect1.setText("");
             jtxtDailyDose1.setText("");
             jtxtHtui1.setText("");
             jtxtNot1.setText("");
             jtxtSe1.setText("");
             jtxtRN.setText("");
            JtxtPName1.setText("");
            jtxtDoB1.setText("");
            jtxtAoP1.setText("");
            
       
             
    }//GEN-LAST:event_jtxtClearActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicalStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicalStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JtxtPName;
    private javax.swing.JTextField JtxtPName1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> jcmbNT;
    private javax.swing.JLabel jtxtAoP;
    private javax.swing.JTextField jtxtAoP1;
    private javax.swing.JButton jtxtClear;
    private javax.swing.JLabel jtxtDailyDose;
    private javax.swing.JTextField jtxtDailyDose1;
    private javax.swing.JButton jtxtDelete;
    private javax.swing.JLabel jtxtDoB;
    private javax.swing.JTextField jtxtDoB1;
    private javax.swing.JButton jtxtDoctor;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JLabel jtxtDose1;
    private javax.swing.JButton jtxtExit;
    private javax.swing.JLabel jtxtExpDate;
    private javax.swing.JTextField jtxtExpDate1;
    private javax.swing.JTextField jtxtFI;
    private javax.swing.JLabel jtxtFI1;
    private javax.swing.JButton jtxtGP;
    private javax.swing.JLabel jtxtHtui;
    private javax.swing.JTextField jtxtHtui1;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JLabel jtxtIssuedDate1;
    private javax.swing.JButton jtxtLogin;
    private javax.swing.JLabel jtxtLot;
    private javax.swing.JTextField jtxtMedicane;
    private javax.swing.JLabel jtxtMedicane1;
    private javax.swing.JLabel jtxtNot;
    private javax.swing.JTextField jtxtNot1;
    private javax.swing.JLabel jtxtPossibleSideEffect;
    private javax.swing.JTextField jtxtPossibleSideEffect1;
    private javax.swing.JButton jtxtPrescription;
    private javax.swing.JTextField jtxtRN;
    private javax.swing.JLabel jtxtRef;
    private javax.swing.JLabel jtxtSe;
    private javax.swing.JTextField jtxtSe1;
    private javax.swing.JButton jtxtUpdate;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables

 

  
}
